# GitHub Action yang lebih simpel dan modern
name: Generate Snake

on:
  schedule:
    # Berjalan setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Menggunakan versi terbaru

      - uses: Platane/snk@v3
        with:
          # PENTING: Username sudah benar
          github_user_name: NgrhDn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3 # Menggunakan versi terbaru
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
