# GitHub Action dengan izin yang sudah diperbaiki
name: Generate Snake

# BARIS BARU DI SINI: Memberikan izin tulis ke Action
permissions:
  contents: write

on:
  schedule:
    # Berjalan setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: NgrhDn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
